---
title: "Introduction to the Tidyverse"
author: "David Mawdsley<p>University of Manchester<p>Northwest Universities R Day - 31 October 2018"
output: 
  revealjs::revealjs_presentation:
    center: false
    transition: fade
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Introduction

* Workshop aims 
* Teaching methods


## Workshop aims

* To introduce the main components of the [Tidyverse](https://www.tidyverse.org)
	+ readr (to read files)
	+ dplyr (to manipulate data)
	+ ggplot2 (to make graphs)
	
* Assumes a basic knowledge of R
* We haven't got time to cover all of the tidyverse, e.g. forcats, purrr, modelr 

## Workshop history

* The workshop is based on UoM's [Data Analysis Using R](https://uomresearchit.github.io/r-tidyverse-intro/) full day course
  	+ The notes for this are always online and publicly accessible
* That course is based on [Software Carpentry's](https://software-carpentry.org) [R for reproducible scientific research](http://swcarpentry.github.io/r-novice-gapminder/) course
    

## How the workshop works

* The course is _interactive_
    + These are the only slides
* Course notes
    + Try to type-along without the notes
    + All the code is in the notes (Extras menu); you can cut and paste this into RStudio.
    + The workshop materials will remain online after the course.


##  Let's get started

https://uomresearchit.github.io/r-day-workshop/
